export const user = state => state.user
export const pcn = state => state.pcn
export const isMPP = state => state.isMPP
export const allPCN = state => state.allPCN
export const allClasses = state => state.allClasses
export const allFeatures = state => state.allFeatures
export const allAccesses = state => state.allAccesses
export const selectedPermission = state => state.selectedPermission
export const selectedPlan = state => state.selectedPlan
export const selectedPlanData = state => state.selectedPlanData
export const planSetupData = state => state.planSetupData
export const selectedProvider = state => state.selectedProvider
export const selectedMppDrug = state => state.selectedMppDrug
export const selectedPrescriber = state => state.selectedPrescriber
export const selectedChain = state => state.selectedChain
export const providerSetupData = state => state.providerSetupData
export const networkParamSetupData = state => state.networkParamSetupData
export const memberFormType = state => state.memberFormType
export const selectedMember = state => state.selectedMember
export const selectedPlanMembers = state => state.selectedPlanMembers
export const memberPlanLists = state => state.memberPlanLists
export const drugSetupData = state => state.drugSetupData
export const groupInformation = state => state.groupInformation
export const claimInfo = state => state.claimInfo
export const claimSetupData = state => state.claimSetupData
export const allSpecialPrograms = state => state.allSpecialPrograms
export const groupEditInfo = state => state.groupEditInfo
export const isUpdateStatus = state => state.isUpdateStatus
export const selectedGroupFilter = state => state.selectedGroupFilter
