export const PricingSourceTypeDescriptions = [
  "Undefined",
  "No Dollar claims",
  "Standard Hospice Pricing",
  "Authorization Amount",
  "Zero Balance",
  "Copay Adjustment",
  "Gross Amount Due",
  "Manual Edit",
  "Senior Discount",
  "Group MAC",
  "HCFA MAC",
  "Ingredient Cost Submitted",
  "ER Kit Special Pricing",
  "Minimum Claim Amount",
  "D.0 Compound Pricing",
  "Other",
  "Pricing Parameters",
  "Quantity Discount",
  "Reject",
  "Submitted Patient Paid Amount",
  "Contract MAC",
  "Usual and Customary Charge",
  "Avacare Pricing",
  "Special Program",
  "DRX Cap",
  "Regional Pricing",
  "Contract Parameters"
]

export const ProductTypeDescriptions = [
  "Unknown",
  "Rx/Brand Name",
  "Rx/Generic",
  "Surgical/Device",
  "Rx/Repackaged Brand Name Product",
  "Rx/Branded Generic",
  "Reserved",
  "OTC/Brand Name",
  "OTC/Generic",
  "OTC/Repackaged",
  "Rx/Repackaged Branded Generic Product",
  "Chemical for Compounding",
  "AWP+5%",
  "AWP-10%",
  "AWP-12%",
  "AWP-13%",
  "AWP-15%",
  "AWP-17%",
  "AWP-25%",
  "AWP-30%",
  "AWP-75%",
  "340B Brand Product",
  "340B Generic Product",
  "Alternate Plan Pricing",
  "Compound Drug (Formulary)",
  "Compound Drug (Non-Formulary)",
  "Specialty Compound",
  "Diabetic Supplies",
  "Excluded (SNF)",
  "Fee",
  "House Supply (SNF)",
  "Insulin",
  "Intravenous (SNF)",
  "Kit",
  "Medical Equipment/Procedure",
  "Monthly Fee",
  "Per Diem",
  "IV Push (SNF)",
  "Specialty Drug",
  "Submitted Pricing",
  "Total Parenteral Nutrition",
  "$4 Generic"
]
